apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/jstrachan/myspringbootweb30:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/jstrachan/myspringbootweb30:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: myspringbootweb30
        chartPath: charts/myspringbootweb30
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/jstrachan/myspringbootweb30"
          image.tag: "{{.TAG}}"
